### ISSUE TITLE
distutils.errors.CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by bsivanantham** [Anjum48/rl-examples#1]
/home/balavivek/anaconda3/bin/python "/home/balavivek/Bala/SEM2/High-Dimensional Continuous Control Using Generalized Advantage Estimation/ppo/ppo.py"
Import error. Trying to rebuild mujoco_py.
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /home/balavivek/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py -I/home/balavivek/.mujoco/mjpro150/include -I/home/balavivek/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/balavivek/anaconda3/include/python3.6m -c /home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/cymj.c -o /home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_1.50.1.56_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /home/balavivek/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py -I/home/balavivek/.mujoco/mjpro150/include -I/home/balavivek/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/balavivek/anaconda3/include/python3.6m -c /home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.c -o /home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_1.50.1.56_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.c:1:23: fatal error: GL/osmesa.h: No such file or directory
 #include <GL/osmesa.h>
                       ^
compilation terminated.
Traceback (most recent call last):
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/balavivek/Bala/SEM2/High-Dimensional Continuous Control Using Generalized Advantage Estimation/ppo/ppo.py", line 202, in <module>
    env = gym.make(ENVIRONMENT)
  File "/home/balavivek/gym/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/balavivek/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/balavivek/gym/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/balavivek/gym/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/balavivek/gym/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/home/balavivek/gym/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/__init__.py", line 1, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/builder.py", line 468, in <module>
    cymj = load_cython_ext(mjpro_path)
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/builder.py", line 90, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/builder.py", line 202, in build
    built_so_file_path = self._build_impl()
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/builder.py", line 256, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/builder.py", line 225, in _build_impl
    dist.run_commands()
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/mujoco_py/builder.py", line 125, in build_extensions
    build_ext.build_extensions(self)
  File "/home/balavivek/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/balavivek/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

**Comment by Anjum48** [comment]
It seems like you have an error with the GCC compiler and Mujoco rather than an issue with this repository. I'll close this for now unless you can provide more specific details.
